// AUTO-GENERATED by scripts/generate-pokemon-data.ts — DO NOT EDIT
// Source: @pkmn/dex (Pokemon Showdown data)
import type { PokemonTemplate, PokemonType } from './types';

export interface EvolutionChain {
  id: number;
  stages: { pokemon: PokemonTemplate; killsRequired: number }[];
}

export const EVOLUTION_CHAINS: EvolutionChain[] = [
  // 0: Charmander line
  {
    id: 0,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 4, name: 'Charmander', types: ['fire'] as PokemonType[],
    hp: 39, atk: 52, def: 43, spa: 60, spd: 50, spe: 65, mov: 4,
    moves: [
    { id: 'ember', name: 'Ember', type: 'fire', category: 'special', power: 40, accuracy: 100, pp: 4, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'scratch', name: 'Scratch', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'dragonbreath', name: 'Dragon Breath', type: 'dragon', category: 'special', power: 60, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'willowisp', name: 'Will-O-Wisp', type: 'fire', category: 'status', power: 0, accuracy: 85, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 100, description: 'Burns the target.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 0, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 5, name: 'Charmeleon', types: ['fire'] as PokemonType[],
    hp: 58, atk: 64, def: 58, spa: 80, spd: 65, spe: 80, mov: 4,
    moves: [
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'slash', name: 'Slash', type: 'normal', category: 'physical', power: 70, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'High critical hit ratio.' },
    { id: 'dragonpulse', name: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'willowisp', name: 'Will-O-Wisp', type: 'fire', category: 'status', power: 0, accuracy: 85, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 100, description: 'Burns the target.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 0, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 6, name: 'Charizard', types: ['fire', 'flying'] as PokemonType[],
    hp: 78, atk: 84, def: 78, spa: 109, spd: 85, spe: 100, mov: 5,
    moves: [
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'airslash', name: 'Air Slash', type: 'flying', category: 'special', power: 75, accuracy: 95, pp: 3, range: 2, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'dragonpulse', name: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'willowisp', name: 'Will-O-Wisp', type: 'fire', category: 'status', power: 0, accuracy: 85, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 100, description: 'Burns the target.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 0, evolutionStage: 2
  } },
    ]
  },
  // 1: Squirtle line
  {
    id: 1,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 7, name: 'Squirtle', types: ['water'] as PokemonType[],
    hp: 44, atk: 48, def: 65, spa: 50, spd: 64, spe: 43, mov: 3,
    moves: [
    { id: 'watergun', name: 'Water Gun', type: 'water', category: 'special', power: 40, accuracy: 100, pp: 4, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'tackle', name: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'bite', name: 'Bite', type: 'dark', category: 'physical', power: 60, accuracy: 100, pp: 4, range: 1, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'withdraw', name: 'Withdraw', type: 'water', category: 'status', power: 0, accuracy: 100, pp: 5, range: 0, priority: 0, description: 'Raises the user\'s Defense by 1.' }
    ],
    ability: { id: 'torrent', name: 'Torrent', description: 'Water moves +50% when HP < 33%' },
    evolutionChainId: 1, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 8, name: 'Wartortle', types: ['water'] as PokemonType[],
    hp: 59, atk: 63, def: 80, spa: 65, spd: 80, spe: 58, mov: 3,
    moves: [
    { id: 'waterpulse', name: 'Water Pulse', type: 'water', category: 'special', power: 60, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to confuse the target.' },
    { id: 'bite', name: 'Bite', type: 'dark', category: 'physical', power: 60, accuracy: 100, pp: 4, range: 1, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'icebeam', name: 'Ice Beam', type: 'ice', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'freeze', effectChance: 10, description: '10% chance to freeze the target.' },
    { id: 'withdraw', name: 'Withdraw', type: 'water', category: 'status', power: 0, accuracy: 100, pp: 5, range: 0, priority: 0, description: 'Raises the user\'s Defense by 1.' }
    ],
    ability: { id: 'torrent', name: 'Torrent', description: 'Water moves +50% when HP < 33%' },
    evolutionChainId: 1, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 9, name: 'Blastoise', types: ['water'] as PokemonType[],
    hp: 79, atk: 83, def: 100, spa: 85, spd: 105, spe: 78, mov: 4,
    moves: [
    { id: 'hydropump', name: 'Hydro Pump', type: 'water', category: 'special', power: 110, accuracy: 80, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'icebeam', name: 'Ice Beam', type: 'ice', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'freeze', effectChance: 10, description: '10% chance to freeze the target.' },
    { id: 'flashcannon', name: 'Flash Cannon', type: 'steel', category: 'special', power: 80, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'scald', name: 'Scald', type: 'water', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 30, description: '30% chance to burn the target. Thaws target.' }
    ],
    ability: { id: 'torrent', name: 'Torrent', description: 'Water moves +50% when HP < 33%' },
    evolutionChainId: 1, evolutionStage: 2
  } },
    ]
  },
  // 2: Bulbasaur line
  {
    id: 2,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 1, name: 'Bulbasaur', types: ['grass', 'poison'] as PokemonType[],
    hp: 45, atk: 49, def: 49, spa: 65, spd: 65, spe: 45, mov: 3,
    moves: [
    { id: 'vinewhip', name: 'Vine Whip', type: 'grass', category: 'physical', power: 45, accuracy: 100, pp: 4, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'tackle', name: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'poisonpowder', name: 'Poison Powder', type: 'poison', category: 'status', power: 0, accuracy: 75, pp: 5, range: 2, priority: 0, effect: 'poison', effectChance: 100, description: 'Poisons the target.' },
    { id: 'leechseed', name: 'Leech Seed', type: 'grass', category: 'status', power: 0, accuracy: 90, pp: 2, range: 2, priority: 0, description: '1/8 of target\'s HP is restored to user every turn.' }
    ],
    ability: { id: 'overgrow', name: 'Overgrow', description: 'Grass moves +50% when HP < 33%' },
    evolutionChainId: 2, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 2, name: 'Ivysaur', types: ['grass', 'poison'] as PokemonType[],
    hp: 60, atk: 62, def: 63, spa: 80, spd: 80, spe: 60, mov: 4,
    moves: [
    { id: 'razorleaf', name: 'Razor Leaf', type: 'grass', category: 'physical', power: 55, accuracy: 95, pp: 4, range: 2, priority: 0, description: 'High critical hit ratio. Hits adjacent foes.' },
    { id: 'sludgebomb', name: 'Sludge Bomb', type: 'poison', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'poison', effectChance: 30, description: '30% chance to poison the target.' },
    { id: 'sleeppowder', name: 'Sleep Powder', type: 'grass', category: 'status', power: 0, accuracy: 75, pp: 3, range: 2, priority: 0, effect: 'sleep', effectChance: 100, description: 'Causes the target to fall asleep.' },
    { id: 'leechseed', name: 'Leech Seed', type: 'grass', category: 'status', power: 0, accuracy: 90, pp: 2, range: 2, priority: 0, description: '1/8 of target\'s HP is restored to user every turn.' }
    ],
    ability: { id: 'overgrow', name: 'Overgrow', description: 'Grass moves +50% when HP < 33%' },
    evolutionChainId: 2, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 3, name: 'Venusaur', types: ['grass', 'poison'] as PokemonType[],
    hp: 80, atk: 82, def: 83, spa: 100, spd: 100, spe: 80, mov: 4,
    moves: [
    { id: 'gigadrain', name: 'Giga Drain', type: 'grass', category: 'special', power: 75, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'User recovers 50% of the damage dealt.' },
    { id: 'sludgebomb', name: 'Sludge Bomb', type: 'poison', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'poison', effectChance: 30, description: '30% chance to poison the target.' },
    { id: 'sleeppowder', name: 'Sleep Powder', type: 'grass', category: 'status', power: 0, accuracy: 75, pp: 3, range: 2, priority: 0, effect: 'sleep', effectChance: 100, description: 'Causes the target to fall asleep.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' }
    ],
    ability: { id: 'overgrow', name: 'Overgrow', description: 'Grass moves +50% when HP < 33%' },
    evolutionChainId: 2, evolutionStage: 2
  } },
    ]
  },
  // 3: Pichu line
  {
    id: 3,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 172, name: 'Pichu', types: ['electric'] as PokemonType[],
    hp: 20, atk: 40, def: 15, spa: 35, spd: 35, spe: 60, mov: 4,
    moves: [
    { id: 'thundershock', name: 'Thunder Shock', type: 'electric', category: 'special', power: 40, accuracy: 100, pp: 4, range: 2, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'charm', name: 'Charm', type: 'fairy', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Lowers the target\'s Attack by 2.' },
    { id: 'quickattack', name: 'Quick Attack', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'static', name: 'Static', description: '30% chance to paralyze attacker on contact' },
    evolutionChainId: 3, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 25, name: 'Pikachu', types: ['electric'] as PokemonType[],
    hp: 35, atk: 55, def: 40, spa: 50, spd: 50, spe: 90, mov: 5,
    moves: [
    { id: 'thunderbolt', name: 'Thunderbolt', type: 'electric', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'quickattack', name: 'Quick Attack', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'irontail', name: 'Iron Tail', type: 'steel', category: 'physical', power: 100, accuracy: 75, pp: 3, range: 1, priority: 0, description: '30% chance to lower the target\'s Defense by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'static', name: 'Static', description: '30% chance to paralyze attacker on contact' },
    evolutionChainId: 3, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 26, name: 'Raichu', types: ['electric'] as PokemonType[],
    hp: 60, atk: 90, def: 55, spa: 90, spd: 80, spe: 110, mov: 5,
    moves: [
    { id: 'thunderbolt', name: 'Thunderbolt', type: 'electric', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'focusblast', name: 'Focus Blast', type: 'fighting', category: 'special', power: 120, accuracy: 70, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'surf', name: 'Surf', type: 'water', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dive.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'static', name: 'Static', description: '30% chance to paralyze attacker on contact' },
    evolutionChainId: 3, evolutionStage: 2
  } },
    ]
  },
  // 4: Machop line
  {
    id: 4,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 66, name: 'Machop', types: ['fighting'] as PokemonType[],
    hp: 70, atk: 80, def: 50, spa: 35, spd: 35, spe: 35, mov: 3,
    moves: [
    { id: 'karatechop', name: 'Karate Chop', type: 'fighting', category: 'physical', power: 50, accuracy: 100, pp: 4, range: 1, priority: 0, description: 'High critical hit ratio.' },
    { id: 'rockthrow', name: 'Rock Throw', type: 'rock', category: 'physical', power: 50, accuracy: 90, pp: 3, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'bulkup', name: 'Bulk Up', type: 'fighting', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack and Defense by 1.' }
    ],
    ability: { id: 'guts', name: 'Guts', description: '+50% ATK when statused' },
    evolutionChainId: 4, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 67, name: 'Machoke', types: ['fighting'] as PokemonType[],
    hp: 80, atk: 100, def: 70, spa: 50, spd: 60, spe: 45, mov: 3,
    moves: [
    { id: 'crosschop', name: 'Cross Chop', type: 'fighting', category: 'physical', power: 100, accuracy: 80, pp: 2, range: 1, priority: 0, description: 'High critical hit ratio.' },
    { id: 'thunderpunch', name: 'Thunder Punch', type: 'electric', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'bulkup', name: 'Bulk Up', type: 'fighting', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack and Defense by 1.' }
    ],
    ability: { id: 'guts', name: 'Guts', description: '+50% ATK when statused' },
    evolutionChainId: 4, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 68, name: 'Machamp', types: ['fighting'] as PokemonType[],
    hp: 90, atk: 130, def: 80, spa: 65, spd: 85, spe: 55, mov: 3,
    moves: [
    { id: 'closecombat', name: 'Close Combat', type: 'fighting', category: 'physical', power: 120, accuracy: 100, pp: 2, range: 1, priority: 0, description: 'Lowers the user\'s Defense and Sp. Def by 1.' },
    { id: 'thunderpunch', name: 'Thunder Punch', type: 'electric', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'bulkup', name: 'Bulk Up', type: 'fighting', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack and Defense by 1.' }
    ],
    ability: { id: 'noguard', name: 'No Guard', description: 'All moves always hit (both sides)' },
    evolutionChainId: 4, evolutionStage: 2
  } },
    ]
  },
  // 5: Gastly line
  {
    id: 5,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 92, name: 'Gastly', types: ['ghost', 'poison'] as PokemonType[],
    hp: 30, atk: 35, def: 30, spa: 100, spd: 35, spe: 80, mov: 4,
    moves: [
    { id: 'lick', name: 'Lick', type: 'ghost', category: 'physical', power: 30, accuracy: 100, pp: 4, range: 1, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'sludgebomb', name: 'Sludge Bomb', type: 'poison', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'poison', effectChance: 30, description: '30% chance to poison the target.' },
    { id: 'hypnosis', name: 'Hypnosis', type: 'psychic', category: 'status', power: 0, accuracy: 60, pp: 3, range: 2, priority: 0, effect: 'sleep', effectChance: 100, description: 'Causes the target to fall asleep.' }
    ],
    ability: { id: 'levitate', name: 'Levitate', description: 'Immune to Ground moves, ignores terrain move cost' },
    evolutionChainId: 5, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 93, name: 'Haunter', types: ['ghost', 'poison'] as PokemonType[],
    hp: 45, atk: 50, def: 45, spa: 115, spd: 55, spe: 95, mov: 5,
    moves: [
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'sludgebomb', name: 'Sludge Bomb', type: 'poison', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'poison', effectChance: 30, description: '30% chance to poison the target.' },
    { id: 'darkpulse', name: 'Dark Pulse', type: 'dark', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'hypnosis', name: 'Hypnosis', type: 'psychic', category: 'status', power: 0, accuracy: 60, pp: 3, range: 2, priority: 0, effect: 'sleep', effectChance: 100, description: 'Causes the target to fall asleep.' }
    ],
    ability: { id: 'levitate', name: 'Levitate', description: 'Immune to Ground moves, ignores terrain move cost' },
    evolutionChainId: 5, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 94, name: 'Gengar', types: ['ghost', 'poison'] as PokemonType[],
    hp: 60, atk: 65, def: 60, spa: 130, spd: 75, spe: 110, mov: 5,
    moves: [
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'sludgebomb', name: 'Sludge Bomb', type: 'poison', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'poison', effectChance: 30, description: '30% chance to poison the target.' },
    { id: 'focusblast', name: 'Focus Blast', type: 'fighting', category: 'special', power: 120, accuracy: 70, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'hypnosis', name: 'Hypnosis', type: 'psychic', category: 'status', power: 0, accuracy: 60, pp: 3, range: 2, priority: 0, effect: 'sleep', effectChance: 100, description: 'Causes the target to fall asleep.' }
    ],
    ability: { id: 'levitate', name: 'Levitate', description: 'Immune to Ground moves, ignores terrain move cost' },
    evolutionChainId: 5, evolutionStage: 2
  } },
    ]
  },
  // 6: Dratini line
  {
    id: 6,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 147, name: 'Dratini', types: ['dragon'] as PokemonType[],
    hp: 41, atk: 64, def: 45, spa: 50, spd: 50, spe: 50, mov: 3,
    moves: [
    { id: 'dragonbreath', name: 'Dragon Breath', type: 'dragon', category: 'special', power: 60, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'aquatail', name: 'Aqua Tail', type: 'water', category: 'physical', power: 90, accuracy: 90, pp: 2, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'slam', name: 'Slam', type: 'normal', category: 'physical', power: 80, accuracy: 75, pp: 3, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'innerfocus', name: 'Inner Focus', description: 'Cannot be flinched' },
    evolutionChainId: 6, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 148, name: 'Dragonair', types: ['dragon'] as PokemonType[],
    hp: 61, atk: 84, def: 65, spa: 70, spd: 70, spe: 70, mov: 4,
    moves: [
    { id: 'dragonpulse', name: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'aquatail', name: 'Aqua Tail', type: 'water', category: 'physical', power: 90, accuracy: 90, pp: 2, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'icebeam', name: 'Ice Beam', type: 'ice', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, effect: 'freeze', effectChance: 10, description: '10% chance to freeze the target.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'innerfocus', name: 'Inner Focus', description: 'Cannot be flinched' },
    evolutionChainId: 6, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 149, name: 'Dragonite', types: ['dragon', 'flying'] as PokemonType[],
    hp: 91, atk: 134, def: 95, spa: 100, spd: 100, spe: 80, mov: 4,
    moves: [
    { id: 'dragonpulse', name: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'extremespeed', name: 'Extreme Speed', type: 'normal', category: 'physical', power: 80, accuracy: 100, pp: 2, range: 1, priority: 2, description: 'Nearly always goes first.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'fireblast', name: 'Fire Blast', type: 'fire', category: 'special', power: 110, accuracy: 85, pp: 2, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' }
    ],
    ability: { id: 'multiscale', name: 'Multiscale', description: 'Takes 50% damage when at full HP' },
    evolutionChainId: 6, evolutionStage: 2
  } },
    ]
  },
  // 7: Geodude line
  {
    id: 7,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 74, name: 'Geodude', types: ['rock', 'ground'] as PokemonType[],
    hp: 40, atk: 80, def: 100, spa: 30, spd: 30, spe: 20, mov: 2,
    moves: [
    { id: 'rockthrow', name: 'Rock Throw', type: 'rock', category: 'physical', power: 50, accuracy: 90, pp: 3, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'tackle', name: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'bulldoze', name: 'Bulldoze', type: 'ground', category: 'physical', power: 60, accuracy: 100, pp: 3, range: 1, priority: 0, description: '100% chance lower adjacent Pkmn Speed by 1.' },
    { id: 'defensecurl', name: 'Defense Curl', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 5, range: 0, priority: 0, description: 'Raises the user\'s Defense by 1.' }
    ],
    ability: { id: 'sturdy', name: 'Sturdy', description: 'Survives any hit with 1 HP if at full HP' },
    evolutionChainId: 7, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 75, name: 'Graveler', types: ['rock', 'ground'] as PokemonType[],
    hp: 55, atk: 95, def: 115, spa: 45, spd: 45, spe: 35, mov: 3,
    moves: [
    { id: 'rockslide', name: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 2, range: 2, priority: 0, description: '30% chance to make the foe(s) flinch.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'firepunch', name: 'Fire Punch', type: 'fire', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'stealthrock', name: 'Stealth Rock', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hurts foes on switch-in. Factors Rock weakness.' }
    ],
    ability: { id: 'sturdy', name: 'Sturdy', description: 'Survives any hit with 1 HP if at full HP' },
    evolutionChainId: 7, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 76, name: 'Golem', types: ['rock', 'ground'] as PokemonType[],
    hp: 80, atk: 120, def: 130, spa: 55, spd: 65, spe: 45, mov: 3,
    moves: [
    { id: 'stoneedge', name: 'Stone Edge', type: 'rock', category: 'physical', power: 100, accuracy: 80, pp: 2, range: 2, priority: 0, description: 'High critical hit ratio.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'firepunch', name: 'Fire Punch', type: 'fire', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'stealthrock', name: 'Stealth Rock', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hurts foes on switch-in. Factors Rock weakness.' }
    ],
    ability: { id: 'sturdy', name: 'Sturdy', description: 'Survives any hit with 1 HP if at full HP' },
    evolutionChainId: 7, evolutionStage: 2
  } },
    ]
  },
  // 8: Abra line
  {
    id: 8,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 63, name: 'Abra', types: ['psychic'] as PokemonType[],
    hp: 25, atk: 20, def: 15, spa: 105, spd: 55, spe: 90, mov: 5,
    moves: [
    { id: 'confusion', name: 'Confusion', type: 'psychic', category: 'special', power: 50, accuracy: 100, pp: 4, range: 2, priority: 0, description: '10% chance to confuse the target.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'hiddenpowerfire', name: 'Hidden Power Fire', type: 'fire', category: 'special', power: 60, accuracy: 100, pp: 3, range: 2, priority: 0, description: '' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 8, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 64, name: 'Kadabra', types: ['psychic'] as PokemonType[],
    hp: 40, atk: 35, def: 30, spa: 120, spd: 70, spe: 105, mov: 5,
    moves: [
    { id: 'psychic', name: 'Psychic', type: 'psychic', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'energyball', name: 'Energy Ball', type: 'grass', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 8, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 65, name: 'Alakazam', types: ['psychic'] as PokemonType[],
    hp: 55, atk: 50, def: 45, spa: 135, spd: 95, spe: 120, mov: 5,
    moves: [
    { id: 'psychic', name: 'Psychic', type: 'psychic', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'focusblast', name: 'Focus Blast', type: 'fighting', category: 'special', power: 120, accuracy: 70, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 8, evolutionStage: 2
  } },
    ]
  },
  // 9: Riolu line
  {
    id: 9,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 447, name: 'Riolu', types: ['fighting'] as PokemonType[],
    hp: 40, atk: 70, def: 40, spa: 35, spd: 40, spe: 60, mov: 4,
    moves: [
    { id: 'forcepalm', name: 'Force Palm', type: 'fighting', category: 'physical', power: 60, accuracy: 100, pp: 2, range: 1, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'quickattack', name: 'Quick Attack', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'steadfast', name: 'Steadfast', description: '+1 MOV when flinched' },
    evolutionChainId: 9, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 448, name: 'Lucario', types: ['fighting', 'steel'] as PokemonType[],
    hp: 70, atk: 110, def: 70, spa: 115, spd: 70, spe: 90, mov: 5,
    moves: [
    { id: 'aurasphere', name: 'Aura Sphere', type: 'fighting', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'This move does not check accuracy.' },
    { id: 'flashcannon', name: 'Flash Cannon', type: 'steel', category: 'special', power: 80, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'darkpulse', name: 'Dark Pulse', type: 'dark', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'justified', name: 'Justified', description: '+25% ATK when hit by Dark move' },
    evolutionChainId: 9, evolutionStage: 1
  } },
    ]
  },
  // 10: Magikarp line
  {
    id: 10,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 129, name: 'Magikarp', types: ['water'] as PokemonType[],
    hp: 20, atk: 10, def: 55, spa: 15, spd: 20, spe: 80, mov: 4,
    moves: [
    { id: 'splash', name: 'Splash', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 5, range: 0, priority: 0, description: 'No competitive use.' },
    { id: 'tackle', name: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'flail', name: 'Flail', type: 'normal', category: 'physical', power: 0, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'More power the less HP the user has left.' },
    { id: 'bounce', name: 'Bounce', type: 'flying', category: 'physical', power: 85, accuracy: 85, pp: 2, range: 1, priority: 0, effect: 'paralysis', effectChance: 30, description: 'Bounces turn 1. Hits turn 2. 30% paralyze.' }
    ],
    ability: { id: 'swiftswim', name: 'Swift Swim', description: '+2 MOV on Water terrain' },
    evolutionChainId: 10, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 130, name: 'Gyarados', types: ['water', 'flying'] as PokemonType[],
    hp: 95, atk: 125, def: 79, spa: 60, spd: 100, spe: 81, mov: 4,
    moves: [
    { id: 'waterfall', name: 'Waterfall', type: 'water', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'icefang', name: 'Ice Fang', type: 'ice', category: 'physical', power: 65, accuracy: 95, pp: 3, range: 1, priority: 0, description: '10% chance to freeze. 10% chance to flinch.' }
    ],
    ability: { id: 'intimidate', name: 'Intimidate', description: 'Reduces adjacent enemy ATK by 25%' },
    evolutionChainId: 10, evolutionStage: 1
  } },
    ]
  },
  // 11: Larvitar line
  {
    id: 11,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 246, name: 'Larvitar', types: ['rock', 'ground'] as PokemonType[],
    hp: 50, atk: 64, def: 50, spa: 45, spd: 50, spe: 41, mov: 3,
    moves: [
    { id: 'rockslide', name: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 2, range: 2, priority: 0, description: '30% chance to make the foe(s) flinch.' },
    { id: 'bite', name: 'Bite', type: 'dark', category: 'physical', power: 60, accuracy: 100, pp: 4, range: 1, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'sandstorm', name: 'Sandstorm', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'For 5 turns, a sandstorm rages. Rock: 1.5x SpD.' }
    ],
    ability: { id: 'guts', name: 'Guts', description: '+50% ATK when statused' },
    evolutionChainId: 11, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 247, name: 'Pupitar', types: ['rock', 'ground'] as PokemonType[],
    hp: 70, atk: 84, def: 70, spa: 65, spd: 70, spe: 51, mov: 3,
    moves: [
    { id: 'rockslide', name: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 2, range: 2, priority: 0, description: '30% chance to make the foe(s) flinch.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'irondefense', name: 'Iron Defense', type: 'steel', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Defense by 2.' }
    ],
    ability: { id: 'sturdy', name: 'Sturdy', description: 'Survives any hit with 1 HP if at full HP' },
    evolutionChainId: 11, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 248, name: 'Tyranitar', types: ['rock', 'dark'] as PokemonType[],
    hp: 100, atk: 134, def: 110, spa: 95, spd: 100, spe: 61, mov: 4,
    moves: [
    { id: 'stoneedge', name: 'Stone Edge', type: 'rock', category: 'physical', power: 100, accuracy: 80, pp: 2, range: 2, priority: 0, description: 'High critical hit ratio.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'fireblast', name: 'Fire Blast', type: 'fire', category: 'special', power: 110, accuracy: 85, pp: 2, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' }
    ],
    ability: { id: 'sandveil', name: 'Sand Veil', description: '+25% evasion on Sand terrain' },
    evolutionChainId: 11, evolutionStage: 2
  } },
    ]
  },
  // 12: Scyther line
  {
    id: 12,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 123, name: 'Scyther', types: ['bug', 'flying'] as PokemonType[],
    hp: 70, atk: 110, def: 80, spa: 55, spd: 80, spe: 105, mov: 5,
    moves: [
    { id: 'xscissor', name: 'X-Scissor', type: 'bug', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'aerialace', name: 'Aerial Ace', type: 'flying', category: 'physical', power: 60, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'This move does not check accuracy.' },
    { id: 'quickattack', name: 'Quick Attack', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'technician', name: 'Technician', description: 'Moves with base power ≤60 get +50% power' },
    evolutionChainId: 12, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 212, name: 'Scizor', types: ['bug', 'steel'] as PokemonType[],
    hp: 70, atk: 130, def: 100, spa: 55, spd: 80, spe: 65, mov: 4,
    moves: [
    { id: 'bulletpunch', name: 'Bullet Punch', type: 'steel', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'xscissor', name: 'X-Scissor', type: 'bug', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'technician', name: 'Technician', description: 'Moves with base power ≤60 get +50% power' },
    evolutionChainId: 12, evolutionStage: 1
  } },
    ]
  },
  // 13: Munchlax line
  {
    id: 13,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 446, name: 'Munchlax', types: ['normal'] as PokemonType[],
    hp: 135, atk: 85, def: 40, spa: 40, spd: 85, spe: 5, mov: 2,
    moves: [
    { id: 'bodyslam', name: 'Body Slam', type: 'normal', category: 'physical', power: 85, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'firepunch', name: 'Fire Punch', type: 'fire', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'rest', name: 'Rest', type: 'psychic', category: 'status', power: 0, accuracy: 100, pp: 2, range: 0, priority: 0, description: 'User sleeps 2 turns and restores HP and status.' }
    ],
    ability: { id: 'thickfat', name: 'Thick Fat', description: 'Fire/Ice damage -50%' },
    evolutionChainId: 13, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 143, name: 'Snorlax', types: ['normal'] as PokemonType[],
    hp: 160, atk: 110, def: 65, spa: 65, spd: 110, spe: 30, mov: 3,
    moves: [
    { id: 'bodyslam', name: 'Body Slam', type: 'normal', category: 'physical', power: 85, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'rest', name: 'Rest', type: 'psychic', category: 'status', power: 0, accuracy: 100, pp: 2, range: 0, priority: 0, description: 'User sleeps 2 turns and restores HP and status.' }
    ],
    ability: { id: 'thickfat', name: 'Thick Fat', description: 'Fire/Ice damage -50%' },
    evolutionChainId: 13, evolutionStage: 1
  } },
    ]
  },
  // 14: Beldum line
  {
    id: 14,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 374, name: 'Beldum', types: ['steel', 'psychic'] as PokemonType[],
    hp: 40, atk: 55, def: 80, spa: 35, spd: 60, spe: 30, mov: 3,
    moves: [
    { id: 'takedown', name: 'Take Down', type: 'normal', category: 'physical', power: 90, accuracy: 85, pp: 3, range: 1, priority: 0, description: 'Has 1/4 recoil.' },
    { id: 'zenheadbutt', name: 'Zen Headbutt', type: 'psychic', category: 'physical', power: 80, accuracy: 90, pp: 3, range: 1, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'irondefense', name: 'Iron Defense', type: 'steel', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Defense by 2.' },
    { id: 'headbutt', name: 'Headbutt', type: 'normal', category: 'physical', power: 70, accuracy: 100, pp: 3, range: 1, priority: 0, description: '30% chance to make the target flinch.' }
    ],
    ability: { id: 'clearbody', name: 'Clear Body', description: 'Prevents stat reduction' },
    evolutionChainId: 14, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 375, name: 'Metang', types: ['steel', 'psychic'] as PokemonType[],
    hp: 60, atk: 75, def: 100, spa: 55, spd: 80, spe: 50, mov: 3,
    moves: [
    { id: 'meteormash', name: 'Meteor Mash', type: 'steel', category: 'physical', power: 90, accuracy: 90, pp: 2, range: 1, priority: 0, description: '20% chance to raise the user\'s Attack by 1.' },
    { id: 'zenheadbutt', name: 'Zen Headbutt', type: 'psychic', category: 'physical', power: 80, accuracy: 90, pp: 3, range: 1, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'bulletpunch', name: 'Bullet Punch', type: 'steel', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'stealthrock', name: 'Stealth Rock', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hurts foes on switch-in. Factors Rock weakness.' }
    ],
    ability: { id: 'clearbody', name: 'Clear Body', description: 'Prevents stat reduction' },
    evolutionChainId: 14, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 376, name: 'Metagross', types: ['steel', 'psychic'] as PokemonType[],
    hp: 80, atk: 135, def: 130, spa: 95, spd: 90, spe: 70, mov: 4,
    moves: [
    { id: 'meteormash', name: 'Meteor Mash', type: 'steel', category: 'physical', power: 90, accuracy: 90, pp: 2, range: 1, priority: 0, description: '20% chance to raise the user\'s Attack by 1.' },
    { id: 'zenheadbutt', name: 'Zen Headbutt', type: 'psychic', category: 'physical', power: 80, accuracy: 90, pp: 3, range: 1, priority: 0, description: '20% chance to make the target flinch.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'bulletpunch', name: 'Bullet Punch', type: 'steel', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' }
    ],
    ability: { id: 'clearbody', name: 'Clear Body', description: 'Prevents stat reduction' },
    evolutionChainId: 14, evolutionStage: 2
  } },
    ]
  },
  // 15: Trapinch line
  {
    id: 15,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 328, name: 'Trapinch', types: ['ground'] as PokemonType[],
    hp: 45, atk: 100, def: 45, spa: 45, spd: 45, spe: 10, mov: 2,
    moves: [
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'crunch', name: 'Crunch', type: 'dark', category: 'physical', power: 80, accuracy: 100, pp: 3, range: 1, priority: 0, description: '20% chance to lower the target\'s Defense by 1.' },
    { id: 'rockslide', name: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 2, range: 2, priority: 0, description: '30% chance to make the foe(s) flinch.' },
    { id: 'sandstorm', name: 'Sandstorm', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'For 5 turns, a sandstorm rages. Rock: 1.5x SpD.' }
    ],
    ability: { id: 'sandveil', name: 'Sand Veil', description: '+25% evasion on Sand terrain' },
    evolutionChainId: 15, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 329, name: 'Vibrava', types: ['ground', 'dragon'] as PokemonType[],
    hp: 50, atk: 70, def: 50, spa: 50, spd: 50, spe: 70, mov: 4,
    moves: [
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'dragonbreath', name: 'Dragon Breath', type: 'dragon', category: 'special', power: 60, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 30, description: '30% chance to paralyze the target.' },
    { id: 'bugbuzz', name: 'Bug Buzz', type: 'bug', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'sandstorm', name: 'Sandstorm', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'For 5 turns, a sandstorm rages. Rock: 1.5x SpD.' }
    ],
    ability: { id: 'levitate', name: 'Levitate', description: 'Immune to Ground moves, ignores terrain move cost' },
    evolutionChainId: 15, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 330, name: 'Flygon', types: ['ground', 'dragon'] as PokemonType[],
    hp: 80, atk: 100, def: 80, spa: 80, spd: 80, spe: 100, mov: 5,
    moves: [
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'dragonpulse', name: 'Dragon Pulse', type: 'dragon', category: 'special', power: 85, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect.' },
    { id: 'fireblast', name: 'Fire Blast', type: 'fire', category: 'special', power: 110, accuracy: 85, pp: 2, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'uturn', name: 'U-turn', type: 'bug', category: 'physical', power: 70, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'User switches out after damaging the target.' }
    ],
    ability: { id: 'levitate', name: 'Levitate', description: 'Immune to Ground moves, ignores terrain move cost' },
    evolutionChainId: 15, evolutionStage: 2
  } },
    ]
  },
  // 16: Chimchar line
  {
    id: 16,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 390, name: 'Chimchar', types: ['fire'] as PokemonType[],
    hp: 44, atk: 58, def: 44, spa: 58, spd: 44, spe: 61, mov: 4,
    moves: [
    { id: 'ember', name: 'Ember', type: 'fire', category: 'special', power: 40, accuracy: 100, pp: 4, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'machpunch', name: 'Mach Punch', type: 'fighting', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'scratch', name: 'Scratch', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'taunt', name: 'Taunt', type: 'dark', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Target can\'t use status moves its next 3 turns.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 16, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 391, name: 'Monferno', types: ['fire', 'fighting'] as PokemonType[],
    hp: 64, atk: 78, def: 52, spa: 78, spd: 52, spe: 81, mov: 4,
    moves: [
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'machpunch', name: 'Mach Punch', type: 'fighting', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'thunderpunch', name: 'Thunder Punch', type: 'electric', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'taunt', name: 'Taunt', type: 'dark', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Target can\'t use status moves its next 3 turns.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 16, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 392, name: 'Infernape', types: ['fire', 'fighting'] as PokemonType[],
    hp: 76, atk: 104, def: 71, spa: 104, spd: 71, spe: 108, mov: 5,
    moves: [
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'closecombat', name: 'Close Combat', type: 'fighting', category: 'physical', power: 120, accuracy: 100, pp: 2, range: 1, priority: 0, description: 'Lowers the user\'s Defense and Sp. Def by 1.' },
    { id: 'thunderpunch', name: 'Thunder Punch', type: 'electric', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'machpunch', name: 'Mach Punch', type: 'fighting', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' }
    ],
    ability: { id: 'blaze', name: 'Blaze', description: 'Fire moves +50% when HP < 33%' },
    evolutionChainId: 16, evolutionStage: 2
  } },
    ]
  },
  // 17: Sneasel line
  {
    id: 17,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 215, name: 'Sneasel', types: ['dark', 'ice'] as PokemonType[],
    hp: 55, atk: 95, def: 55, spa: 35, spd: 75, spe: 115, mov: 5,
    moves: [
    { id: 'icepunch', name: 'Ice Punch', type: 'ice', category: 'physical', power: 75, accuracy: 100, pp: 3, range: 1, priority: 0, effect: 'freeze', effectChance: 10, description: '10% chance to freeze the target.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'quickattack', name: 'Quick Attack', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'innerfocus', name: 'Inner Focus', description: 'Cannot be flinched' },
    evolutionChainId: 17, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 461, name: 'Weavile', types: ['dark', 'ice'] as PokemonType[],
    hp: 70, atk: 120, def: 65, spa: 45, spd: 85, spe: 125, mov: 5,
    moves: [
    { id: 'iciclecrash', name: 'Icicle Crash', type: 'ice', category: 'physical', power: 85, accuracy: 90, pp: 2, range: 1, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'knockoff', name: 'Knock Off', type: 'dark', category: 'physical', power: 65, accuracy: 100, pp: 3, range: 1, priority: 0, description: '1.5x damage if foe holds an item. Removes item.' },
    { id: 'lowkick', name: 'Low Kick', type: 'fighting', category: 'physical', power: 0, accuracy: 100, pp: 3, range: 1, priority: 0, description: 'More power the heavier the target.' },
    { id: 'swordsdance', name: 'Swords Dance', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 3, range: 0, priority: 0, description: 'Raises the user\'s Attack by 2.' }
    ],
    ability: { id: 'pressure', name: 'Pressure', description: 'Enemy moves cost +1 PP' },
    evolutionChainId: 17, evolutionStage: 1
  } },
    ]
  },
  // 18: Swinub line
  {
    id: 18,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 220, name: 'Swinub', types: ['ice', 'ground'] as PokemonType[],
    hp: 50, atk: 50, def: 40, spa: 30, spd: 30, spe: 50, mov: 3,
    moves: [
    { id: 'iceshard', name: 'Ice Shard', type: 'ice', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'tackle', name: 'Tackle', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'mudslap', name: 'Mud-Slap', type: 'ground', category: 'special', power: 20, accuracy: 100, pp: 2, range: 2, priority: 0, description: '100% chance to lower the target\'s accuracy by 1.' }
    ],
    ability: { id: 'thickfat', name: 'Thick Fat', description: 'Fire/Ice damage -50%' },
    evolutionChainId: 18, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 221, name: 'Piloswine', types: ['ice', 'ground'] as PokemonType[],
    hp: 100, atk: 100, def: 80, spa: 60, spd: 60, spe: 50, mov: 3,
    moves: [
    { id: 'iceshard', name: 'Ice Shard', type: 'ice', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'rockslide', name: 'Rock Slide', type: 'rock', category: 'physical', power: 75, accuracy: 90, pp: 2, range: 2, priority: 0, description: '30% chance to make the foe(s) flinch.' },
    { id: 'stealthrock', name: 'Stealth Rock', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hurts foes on switch-in. Factors Rock weakness.' }
    ],
    ability: { id: 'thickfat', name: 'Thick Fat', description: 'Fire/Ice damage -50%' },
    evolutionChainId: 18, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 473, name: 'Mamoswine', types: ['ice', 'ground'] as PokemonType[],
    hp: 110, atk: 130, def: 80, spa: 70, spd: 60, spe: 80, mov: 4,
    moves: [
    { id: 'iciclecrash', name: 'Icicle Crash', type: 'ice', category: 'physical', power: 85, accuracy: 90, pp: 2, range: 1, priority: 0, description: '30% chance to make the target flinch.' },
    { id: 'earthquake', name: 'Earthquake', type: 'ground', category: 'physical', power: 100, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'Hits adjacent Pokemon. Double damage on Dig.' },
    { id: 'iceshard', name: 'Ice Shard', type: 'ice', category: 'physical', power: 40, accuracy: 100, pp: 4, range: 1, priority: 1, description: 'Usually goes first.' },
    { id: 'stealthrock', name: 'Stealth Rock', type: 'rock', category: 'status', power: 0, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'Hurts foes on switch-in. Factors Rock weakness.' }
    ],
    ability: { id: 'thickfat', name: 'Thick Fat', description: 'Fire/Ice damage -50%' },
    evolutionChainId: 18, evolutionStage: 2
  } },
    ]
  },
  // 19: Ralts line
  {
    id: 19,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 280, name: 'Ralts', types: ['psychic', 'fairy'] as PokemonType[],
    hp: 28, atk: 25, def: 25, spa: 45, spd: 35, spe: 40, mov: 3,
    moves: [
    { id: 'confusion', name: 'Confusion', type: 'psychic', category: 'special', power: 50, accuracy: 100, pp: 4, range: 2, priority: 0, description: '10% chance to confuse the target.' },
    { id: 'disarmingvoice', name: 'Disarming Voice', type: 'fairy', category: 'special', power: 40, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'This move does not check accuracy. Hits foes.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'trace', name: 'Trace', description: 'Copies the opponent\'s ability when entering combat' },
    evolutionChainId: 19, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 281, name: 'Kirlia', types: ['psychic', 'fairy'] as PokemonType[],
    hp: 38, atk: 35, def: 35, spa: 65, spd: 55, spe: 50, mov: 3,
    moves: [
    { id: 'psychic', name: 'Psychic', type: 'psychic', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'dazzlinggleam', name: 'Dazzling Gleam', type: 'fairy', category: 'special', power: 80, accuracy: 100, pp: 2, range: 2, priority: 0, description: 'No additional effect. Hits adjacent foes.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'trace', name: 'Trace', description: 'Copies the opponent\'s ability when entering combat' },
    evolutionChainId: 19, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 282, name: 'Gardevoir', types: ['psychic', 'fairy'] as PokemonType[],
    hp: 68, atk: 65, def: 65, spa: 125, spd: 115, spe: 80, mov: 4,
    moves: [
    { id: 'psychic', name: 'Psychic', type: 'psychic', category: 'special', power: 90, accuracy: 100, pp: 2, range: 2, priority: 0, description: '10% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'moonblast', name: 'Moonblast', type: 'fairy', category: 'special', power: 95, accuracy: 100, pp: 3, range: 2, priority: 0, description: '30% chance to lower the target\'s Sp. Atk by 1.' },
    { id: 'shadowball', name: 'Shadow Ball', type: 'ghost', category: 'special', power: 80, accuracy: 100, pp: 3, range: 2, priority: 0, description: '20% chance to lower the target\'s Sp. Def by 1.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' }
    ],
    ability: { id: 'trace', name: 'Trace', description: 'Copies the opponent\'s ability when entering combat' },
    evolutionChainId: 19, evolutionStage: 2
  } },
    ]
  },
  // 20: Cleffa line
  {
    id: 20,
    stages: [
      { killsRequired: 0, pokemon: {
    id: 173, name: 'Cleffa', types: ['fairy'] as PokemonType[],
    hp: 50, atk: 25, def: 28, spa: 45, spd: 55, spe: 15, mov: 2,
    moves: [
    { id: 'pound', name: 'Pound', type: 'normal', category: 'physical', power: 40, accuracy: 100, pp: 5, range: 1, priority: 0, description: 'No additional effect.' },
    { id: 'disarmingvoice', name: 'Disarming Voice', type: 'fairy', category: 'special', power: 40, accuracy: 100, pp: 3, range: 2, priority: 0, description: 'This move does not check accuracy. Hits foes.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' },
    { id: 'wish', name: 'Wish', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 2, range: 0, priority: 0, description: 'Next turn, 50% of the user\'s max HP is restored.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 20, evolutionStage: 0
  } },
      { killsRequired: 2, pokemon: {
    id: 35, name: 'Clefairy', types: ['fairy'] as PokemonType[],
    hp: 70, atk: 45, def: 48, spa: 60, spd: 65, spe: 35, mov: 3,
    moves: [
    { id: 'moonblast', name: 'Moonblast', type: 'fairy', category: 'special', power: 95, accuracy: 100, pp: 3, range: 2, priority: 0, description: '30% chance to lower the target\'s Sp. Atk by 1.' },
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'thunderwave', name: 'Thunder Wave', type: 'electric', category: 'status', power: 0, accuracy: 90, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 100, description: 'Paralyzes the target.' },
    { id: 'wish', name: 'Wish', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 2, range: 0, priority: 0, description: 'Next turn, 50% of the user\'s max HP is restored.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 20, evolutionStage: 1
  } },
      { killsRequired: 4, pokemon: {
    id: 36, name: 'Clefable', types: ['fairy'] as PokemonType[],
    hp: 95, atk: 70, def: 73, spa: 95, spd: 90, spe: 60, mov: 4,
    moves: [
    { id: 'moonblast', name: 'Moonblast', type: 'fairy', category: 'special', power: 95, accuracy: 100, pp: 3, range: 2, priority: 0, description: '30% chance to lower the target\'s Sp. Atk by 1.' },
    { id: 'flamethrower', name: 'Flamethrower', type: 'fire', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'burn', effectChance: 10, description: '10% chance to burn the target.' },
    { id: 'thunderbolt', name: 'Thunderbolt', type: 'electric', category: 'special', power: 90, accuracy: 100, pp: 3, range: 2, priority: 0, effect: 'paralysis', effectChance: 10, description: '10% chance to paralyze the target.' },
    { id: 'wish', name: 'Wish', type: 'normal', category: 'status', power: 0, accuracy: 100, pp: 2, range: 0, priority: 0, description: 'Next turn, 50% of the user\'s max HP is restored.' }
    ],
    ability: { id: 'magicguard', name: 'Magic Guard', description: 'Takes no damage from status effects' },
    evolutionChainId: 20, evolutionStage: 2
  } },
    ]
  },
];

export function getBaseFormPokemon(): PokemonTemplate[] {
  return EVOLUTION_CHAINS.map(chain => chain.stages[0].pokemon);
}

export function getRandomBasePokemon(excludeIds: Set<number> = new Set()): PokemonTemplate {
  const basePool = getBaseFormPokemon();
  const available = basePool.filter(p => !excludeIds.has(p.id));
  if (available.length === 0) return basePool[Math.floor(Math.random() * basePool.length)];
  return available[Math.floor(Math.random() * available.length)];
}

export function getNextEvolution(currentPokemon: PokemonTemplate, currentKills: number): PokemonTemplate | null {
  if (currentPokemon.evolutionChainId === undefined) return null;
  const chain = EVOLUTION_CHAINS[currentPokemon.evolutionChainId];
  if (!chain) return null;
  const currentStageIndex = chain.stages.findIndex(s => s.pokemon.id === currentPokemon.id);
  if (currentStageIndex === -1 || currentStageIndex >= chain.stages.length - 1) return null;
  const nextStage = chain.stages[currentStageIndex + 1];
  if (currentKills >= nextStage.killsRequired) return nextStage.pokemon;
  return null;
}

export function canEvolve(pokemon: PokemonTemplate, kills: number): boolean {
  return getNextEvolution(pokemon, kills) !== null;
}
